### ISSUE TITLE
Add extra pip instruction to README 

### ISSUE THREAD

**Issue by brynbellomy** [r0x0r/lycheeupload#2]
I followed the install instructions for OS X but ran into the problem mentioned in the article linked below.  There's a fix in the article too, though, so maybe add the `pip install --allow-external mysql-connector-python mysql-connector-python` command to the README?

The article — https://geert.vanderkelen.org/installing-coy-using-pip/

Awesome project, by the way!

**Comment by r0x0r** [comment]
Thanks for pointing this out. :)
I have updated the README.
